defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:latest
        environment:
        - PGHOST: 127.0.0.1
        - PGUSER: root
        - PGDB: sqlmap
    - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER: root
        - POSTGRES_DB: sqlmap

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - run: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace


  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test

  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run coverage

  test-security:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:security

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - test-security:
          requires:
            - build
      - coverage:
          requires:
            - lint
            - test